// Simulation d'une base de données de bibliothèque
export const libraryBooks = [
  {
    id: 1,
    title: "Introduction aux Algorithmes",
    author: "Thomas H. Cormen",
    category: "Informatique",
    available: true,
    borrowedBy: null,
    dueDate: null,
    image: "/placeholder.svg?height=120&width=80",
    description: "Un ouvrage de référence sur les algorithmes et leur complexité",
    isbn: "978-0262033848",
    publisher: "MIT Press",
    year: 2009,
    relatedModules: ["structure-donnees-c"],
  },
  {
    id: 2,
    title: "Calcul: Transcendantales Précoces",
    author: "James Stewart",
    category: "Mathématiques",
    available: true,
    borrowedBy: null,
    dueDate: null,
    image: "/placeholder.svg?height=120&width=80",
    description: "Manuel complet de calcul différentiel et intégral",
    isbn: "978-1285741550",
    publisher: "Cengage Learning",
    year: 2015,
    relatedModules: ["analyse4"],
  },
  {
    id: 3,
    title: "Physique pour Scientifiques et Ingénieurs",
    author: "Serway & Jewett",
    category: "Physique",
    available: false,
    borrowedBy: 2,
    dueDate: "2023-11-15T00:00:00Z",
    image: "/placeholder.svg?height=120&width=80",
    description: "Manuel couvrant tous les aspects de la physique pour l'ingénierie",
    isbn: "978-1337553292",
    publisher: "Cengage Learning",
    year: 2018,
    relatedModules: [],
  },
  {
    id: 4,
    title: "Chimie Organique",
    author: "Paula Y. Bruice",
    category: "Chimie",
    available: true,
    borrowedBy: null,
    dueDate: null,
    image: "/placeholder.svg?height=120&width=80",
    description: "Introduction complète à la chimie organique",
    isbn: "978-0134042282",
    publisher: "Pearson",
    year: 2016,
    relatedModules: [],
  },
  {
    id: 5,
    title: "Structures de Données et Algorithmes en Python",
    author: "Michael T. Goodrich",
    category: "Informatique",
    available: true,
    borrowedBy: null,
    dueDate: null,
    image: "/placeholder.svg?height=120&width=80",
    description: "Implémentation des structures de données en Python",
    isbn: "978-1118290279",
    publisher: "Wiley",
    year: 2013,
    relatedModules: ["structure-donnees-c"],
  },
  {
    id: 6,
    title: "Algèbre Linéaire et ses Applications",
    author: "Gilbert Strang",
    category: "Mathématiques",
    available: false,
    borrowedBy: 1,
    dueDate: "2023-11-10T00:00:00Z",
    image: "/placeholder.svg?height=120&width=80",
    description: "Ouvrage de référence en algèbre linéaire",
    isbn: "978-0030105678",
    publisher: "Academic Press",
    year: 2006,
    relatedModules: ["algebre4"],
  },
  {
    id: 7,
    title: "Droit de l'Environnement",
    author: "Michel Prieur",
    category: "Droit",
    available: true,
    borrowedBy: null,
    dueDate: null,
    image: "/placeholder.svg?height=120&width=80",
    description: "Manuel de référence sur le droit environnemental",
    isbn: "978-2247152711",
    publisher: "Dalloz",
    year: 2019,
    relatedModules: ["droit-environnement"],
  },
  {
    id: 8,
    title: "Électronique Analogique: Théorie et Pratique",
    author: "Jean-Pierre Cambronne",
    category: "Électronique",
    available: true,
    borrowedBy: null,
    dueDate: null,
    image: "/placeholder.svg?height=120&width=80",
    description: "Cours complet d'électronique analogique avec exercices",
    isbn: "978-2100582969",
    publisher: "Dunod",
    year: 2016,
    relatedModules: ["electronique-analogique"],
  },
  {
    id: 9,
    title: "Systèmes Numériques: Conception et Applications",
    author: "Roland Katz",
    category: "Électronique",
    available: true,
    borrowedBy: null,
    dueDate: null,
    image: "/placeholder.svg?height=120&width=80",
    description: "Introduction aux systèmes numériques et à leur conception",
    isbn: "978-2100563456",
    publisher: "Dunod",
    year: 2017,
    relatedModules: ["electronique-numerique"],
  },
  {
    id: 10,
    title: "Probabilités et Statistiques pour l'Ingénieur",
    author: "Jean-Yves Tourneret",
    category: "Mathématiques",
    available: true,
    borrowedBy: null,
    dueDate: null,
    image: "/placeholder.svg?height=120&width=80",
    description: "Cours et exercices de probabilités et statistiques",
    isbn: "978-2340013797",
    publisher: "Ellipses",
    year: 2018,
    relatedModules: ["probabilites-statistique"],
  },
]
