// Simulation d'une base de données de matériaux pédagogiques
export const moduleMaterials: Record<string, any[]> = {
  algebre4: [
    {
      id: "1",
      moduleId: "algebre4",
      title: "Polycopié du cours d'Algèbre 4",
      type: "PDF",
      description: "Document principal du cours couvrant tous les chapitres",
      url: "/materials/algebre4/polycopie.pdf",
      createdAt: "2023-09-01T08:00:00Z",
    },
    {
      id: "2",
      moduleId: "algebre4",
      title: "Exercices corrigés - Espaces vectoriels",
      type: "PDF",
      description: "Série d'exercices avec solutions détaillées",
      url: "/materials/algebre4/exercices-espaces-vectoriels.pdf",
      createdAt: "2023-09-05T10:30:00Z",
    },
    {
      id: "3",
      moduleId: "algebre4",
      title: "Annales d'examens 2023",
      type: "PDF",
      description: "Sujets d'examens des années précédentes avec corrigés",
      url: "/materials/algebre4/annales-2023.pdf",
      createdAt: "2023-09-10T14:15:00Z",
    },
  ],
  analyse4: [
    {
      id: "4",
      moduleId: "analyse4",
      title: "Polycopié du cours d'Analyse 4",
      type: "PDF",
      description: "Document principal du cours couvrant tous les chapitres",
      url: "/materials/analyse4/polycopie.pdf",
      createdAt: "2023-09-02T09:00:00Z",
    },
    {
      id: "5",
      moduleId: "analyse4",
      title: "Exercices corrigés - Fonctions holomorphes",
      type: "PDF",
      description: "Série d'exercices avec solutions détaillées",
      url: "/materials/analyse4/exercices-fonctions-holomorphes.pdf",
      createdAt: "2023-09-06T11:45:00Z",
    },
    {
      id: "6",
      moduleId: "analyse4",
      title: "Vidéo - Introduction aux séries de Laurent",
      type: "VIDEO",
      description: "Présentation vidéo des concepts fondamentaux",
      url: "/materials/analyse4/series-laurent.mp4",
      createdAt: "2023-09-12T16:30:00Z",
    },
  ],
  anglais3: [
    {
      id: "7",
      moduleId: "anglais3",
      title: "Support de cours - Technical Writing",
      type: "PDF",
      description: "Guide de rédaction technique en anglais",
      url: "/materials/anglais3/technical-writing.pdf",
      createdAt: "2023-09-03T10:00:00Z",
    },
    {
      id: "8",
      moduleId: "anglais3",
      title: "Exercices d'écoute - Présentations scientifiques",
      type: "AUDIO",
      description: "Fichiers audio avec questions de compréhension",
      url: "/materials/anglais3/listening-exercises.zip",
      createdAt: "2023-09-07T13:00:00Z",
    },
  ],
  "droit-environnement": [
    {
      id: "9",
      moduleId: "droit-environnement",
      title: "Polycopié - Principes du droit environnemental",
      type: "PDF",
      description: "Introduction aux concepts juridiques environnementaux",
      url: "/materials/droit-environnement/principes.pdf",
      createdAt: "2023-09-04T11:00:00Z",
    },
    {
      id: "10",
      moduleId: "droit-environnement",
      title: "Études de cas - Contentieux environnementaux",
      type: "PDF",
      description: "Analyse de jurisprudences récentes",
      url: "/materials/droit-environnement/etudes-cas.pdf",
      createdAt: "2023-09-08T14:15:00Z",
    },
  ],
  "electronique-analogique": [
    {
      id: "11",
      moduleId: "electronique-analogique",
      title: "Polycopié - Amplificateurs opérationnels",
      type: "PDF",
      description: "Théorie et applications des AOP",
      url: "/materials/electronique-analogique/ampli-op.pdf",
      createdAt: "2023-09-05T09:30:00Z",
    },
    {
      id: "12",
      moduleId: "electronique-analogique",
      title: "TP - Filtres analogiques",
      type: "PDF",
      description: "Instructions pour les travaux pratiques",
      url: "/materials/electronique-analogique/tp-filtres.pdf",
      createdAt: "2023-09-09T15:45:00Z",
    },
  ],
}
