// Simulation d'une base de données de modules
export const modules = [
  {
    id: "algebre4",
    title: "Algèbre 4",
    description: "Approfondissement des concepts algébriques avancés",
    professor: "Pr. MAZGOURI ZAKARIA",
    credits: 1,
  },
  {
    id: "analyse4",
    title: "Analyse 4",
    description: "Étude des fonctions complexes et équations différentielles",
    professor: "Dr. Sophie Laurent",
    credits: 4,
  },
  {
    id: "anglais3",
    title: "Anglais 3",
    description: "Communication professionnelle et technique en anglais",
    professor: "Prof. Emily Johnson",
    credits: 2,
  },
  {
    id: "droit-environnement",
    title: "Droit Environnement",
    description: "Législation et réglementation environnementale",
    professor: "Me. Claire Moreau",
    credits: 3,
  },
  {
    id: "electronique-analogique",
    title: "Electronique Analogique",
    description: "Conception et analyse de circuits analogiques",
    professor: "Prof. Thomas Leroy",
    credits: 4,
  },
  {
    id: "electronique-numerique",
    title: "Electronique Numérique",
    description: "Systèmes numériques et conception logique",
    professor: "Dr. Philippe Blanc",
    credits: 4,
  },
  {
    id: "espagnol",
    title: "Espagnol",
    description: "Compétences linguistiques et culturelles en espagnol",
    professor: "Prof. Maria Rodriguez",
    credits: 2,
  },
  {
    id: "probabilites-statistique",
    title: "Probabilités et Statistique",
    description: "Analyse de données et modèles probabilistes",
    professor: "Dr. Julien Mercier",
    credits: 4,
  },
  {
    id: "structure-donnees-c",
    title: "Structure des Données en C",
    description: "Implémentation et optimisation des structures de données",
    professor: "Prof. Nicolas Petit",
    credits: 4,
  },
  {
    id: "systeme-exploitation",
    title: "Système d'Exploitation",
    description: "Architecture et fonctionnement des systèmes d'exploitation",
    professor: "Dr. Antoine Durand",
    credits: 4,
  },
]

// Détails supplémentaires pour chaque module
export const moduleDetails = {
  algebre4: {
    chapters: [
      "Espaces vectoriels avancés",
      "Formes bilinéaires et quadratiques",
      "Théorie des groupes",
      "Anneaux et corps",
      "Applications linéaires",
    ],
    resources: ["Polycopié du cours", "Exercices corrigés", "Annales d'examens"],
    schedule: "Lundi 9h-12h, Salle A305",
    examDate: "2024-06-15T09:00:00Z",
  },
  analyse4: {
    chapters: [
      "Fonctions holomorphes",
      "Intégrales de contour",
      "Séries de Laurent",
      "Théorème des résidus",
      "Équations différentielles complexes",
    ],
    resources: ["Polycopié du cours", "Exercices corrigés", "Annales d'examens"],
    schedule: "Mardi 14h-17h, Salle B201",
    examDate: "2024-06-18T14:00:00Z",
  },
  anglais3: {
    chapters: [
      "Rédaction technique",
      "Présentation orale",
      "Vocabulaire scientifique",
      "Compréhension de documents techniques",
      "Communication professionnelle",
    ],
    resources: ["Supports de cours", "Exercices d'écoute", "Articles scientifiques"],
    schedule: "Mercredi 10h-12h, Salle C102",
    examDate: "2024-06-20T10:00:00Z",
  },
  "droit-environnement": {
    chapters: [
      "Principes fondamentaux du droit de l'environnement",
      "Réglementation des installations classées",
      "Droit de l'eau",
      "Gestion des déchets",
      "Responsabilité environnementale",
    ],
    resources: ["Code de l'environnement", "Études de cas", "Jurisprudence"],
    schedule: "Jeudi 13h-16h, Salle D105",
    examDate: "2024-06-22T13:00:00Z",
  },
  "electronique-analogique": {
    chapters: [
      "Amplificateurs opérationnels",
      "Filtres analogiques",
      "Oscillateurs",
      "Convertisseurs A/N et N/A",
      "Circuits non-linéaires",
    ],
    resources: ["Polycopié du cours", "Travaux pratiques", "Simulations"],
    schedule: "Vendredi 9h-12h, Salle TP E201",
    examDate: "2024-06-25T09:00:00Z",
  },
  "electronique-numerique": {
    chapters: [
      "Systèmes combinatoires",
      "Systèmes séquentiels",
      "Architectures FPGA",
      "Langages de description matérielle",
      "Conception de systèmes numériques",
    ],
    resources: ["Polycopié du cours", "Travaux pratiques", "Projets"],
    schedule: "Lundi 14h-17h, Salle TP E202",
    examDate: "2024-06-27T14:00:00Z",
  },
  espagnol: {
    chapters: [
      "Grammaire avancée",
      "Conversation professionnelle",
      "Culture hispanique",
      "Compréhension écrite et orale",
      "Rédaction technique",
    ],
    resources: ["Manuel de cours", "Exercices d'écoute", "Articles"],
    schedule: "Mardi 10h-12h, Salle C103",
    examDate: "2024-06-29T10:00:00Z",
  },
  "probabilites-statistique": {
    chapters: [
      "Probabilités conditionnelles",
      "Variables aléatoires",
      "Lois de probabilité",
      "Statistique inférentielle",
      "Tests d'hypothèses",
    ],
    resources: ["Polycopié du cours", "Exercices corrigés", "Jeux de données"],
    schedule: "Mercredi 14h-17h, Salle A306",
    examDate: "2024-07-02T14:00:00Z",
  },
  "structure-donnees-c": {
    chapters: ["Tableaux et listes chaînées", "Piles et files", "Arbres binaires", "Tables de hachage", "Graphes"],
    resources: ["Polycopié du cours", "Travaux pratiques", "Projets"],
    schedule: "Jeudi 9h-12h, Salle TP F101",
    examDate: "2024-07-04T09:00:00Z",
  },
  "systeme-exploitation": {
    chapters: ["Processus et threads", "Ordonnancement", "Gestion de la mémoire", "Systèmes de fichiers", "Sécurité"],
    resources: ["Polycopié du cours", "Travaux pratiques", "Projets"],
    schedule: "Vendredi 14h-17h, Salle TP F102",
    examDate: "2024-07-06T14:00:00Z",
  },
}
