// Simulation d'une base de données de modules
export const modules = [
  {
    id: "algebre4",
    title: "Algèbre 4",
    description: "Approfondissement des concepts algébriques avancés",
    professor: "Pr. MAZGOURI ZAKARIA",
    credits: 1,
  },
  {
    id: "analyse4",
    title: "Analyse 4",
    description: "Étude des fonctions complexes et équations différentielles",
    professor: "Pr. JERROUDI AMINE",
    credits: 1,
  },
  {
    id: "anglais3",
    title: "Anglais 3",
    description: "Communication professionnelle et technique en anglais",
    professor: "Pr. DAHBI MANAR",
    credits: 1,
  },
  {
    id: "droit-environnement",
    title: "Droit Environnement",
    description: "Législation et réglementation environnementale",
    professor: "Pr. LAHRECH Khadija",
    credits: 1,
  },
  {
    id: "electronique-analogique",
    title: "Electronique Analogique",
    description: "Conception et analyse de circuits analogiques",
    professor: "Pr. MAZER Said",
    credits: 1,
  },
  {
    id: "electronique-numerique",
    title: "Electronique Numérique",
    description: "Systèmes numériques et conception logique",
    professor: "Pr. MRABTI Mostafa",
    credits: 1,
  },
  {
    id: "espagnol",
    title: "Espagnol",
    description: "Compétences linguistiques et culturelles en espagnol",
    professor: "Pr. KHALID NEJJARI",
    credits: 1,
  },
  {
    id: "probabilites-statistique",
    title: "Probabilités et Statistique",
    description: "Analyse de données et modèles probabilistes",
    professor: "Pr. OUGHDIR LAHCEN",
    credits: 1,
  },
  {
    id: "structure-donnees-c",
    title: "Structure des Données en C",
    description: "Implémentation et optimisation des structures de données",
    professor: "Pr. HRAOUI Said",
    credits: 1,
  },
  {
    id: "systeme-exploitation",
    title: "Système d'Exploitation",
    description: "Architecture et fonctionnement des systèmes d'exploitation",
    professor: "Pr. CHETIOUI Kaouthar",
    credits: 4,
  },
]

// Détails supplémentaires pour chaque module
export const moduleDetails = {
  algebre4: {
    chapters: [
      "Espaces vectoriels avancés",
      "Formes bilinéaires et quadratiques",
      "Théorie des groupes",
      "Anneaux et corps",
      "Applications linéaires",
    ],
    resources: ["Polycopié du cours", "Exercices", " Examen Normal avec correction", "Examen de Rattrapage avec correction"],
    schedule: "Lundi 9h-11h, 0.5, 1.1, 1.4,1.5, AMPHI",
    examDate: "26-05-20255T09:00:00Z",
  },
  analyse4: {
    chapters: [
      "Fonctions holomorphes",
      "Intégrales de contour",
      "Séries de Laurent",
      "Théorème des résidus",
      "Équations différentielles complexes",
    ],
    resources: ["Polycopié du cours", "Exercices corrigés", "Annales d'examens"],
    schedule: "JEUDI 14H30-16H30, 0.5, 1.1, 1.4,1.5, AMPHI",
    examDate: "2024-06-18T14:00:00Z",
  },
  anglais3: {
    chapters: [
      "Rédaction technique",
      "Présentation orale",
      "Vocabulaire scientifique",
      "Compréhension de documents techniques",
      "Communication professionnelle",
    ],
    resources: ["Supports de cours", "Exercices d'écoute", "Articles scientifiques"],
    schedule: "JEUDI 16H45-18H45, 0.5, 1.1, 1.4,1.5, AMPHI",
    examDate: "29/05/2025T10:00:00Z",
  },
  "droit-environnement": {
    chapters: [
      "Principes fondamentaux du droit de l'environnement",
      "Réglementation des installations classées",
      "Droit de l'eau",
      "Gestion des déchets",
      "Responsabilité environnementale",
    ],
    resources: ["Code de l'environnement", "Études de cas", "Jurisprudence"],
    schedule: "VENDREDI 11H15-13H15, 0.5, 1.1, 1.4,1.5, AMPHI",
    examDate: "30/05/2025T13:00:00Z",
  },
  "electronique-analogique": {
    chapters: [
      "Amplificateurs opérationnels",
      "Filtres analogiques",
      "Oscillateurs",
      "Convertisseurs A/N et N/A",
      "Circuits non-linéaires",
    ],
    resources: ["Polycopié du cours", "Travaux pratiques", "Simulations"],
    schedule: "Vendredi 09H00-11H00, 0.5, 1.1, 1.4,1.5, AMPHI",
    examDate: "30/05/2025T09:00:00Z",
  },
  "electronique-numerique": {
    chapters: [
      "Systèmes combinatoires",
      "Systèmes séquentiels",
      "Architectures FPGA",
      "Langages de description matérielle",
      "Conception de systèmes numériques",
    ],
    resources: ["Polycopié du cours", "Travaux pratiques", "Projets"],
    schedule: "MERCREDI 09H00-11H00, 0.5, 1.1, 1.4,1.5, AMPHI",
    examDate: "28/05/2025T14:00:00Z",
  },
  espagnol: {
    chapters: [
      "Grammaire avancée",
      "Conversation professionnelle",
      "Culture hispanique",
      "Compréhension écrite et orale",
      "Rédaction technique",
    ],
    resources: ["Manuel de cours", "Exercices d'écoute", "Articles"],
    schedule: "MERCREDI 11H15-13H15 , 0.5, 1.1, 1.4,1.5, AMPHI",
    examDate: "28/05/2025T10:00:00Z",
  },
  "probabilites-statistique": {
    chapters: [
      "Probabilités conditionnelles",
      "Variables aléatoires",
      "Lois de probabilité",
      "Statistique inférentielle",
      "Tests d'hypothèses",
    ],
    resources: ["Polycopié du cours", "Exercices corrigés", "Jeux de données"],
    schedule: "LUNDI 11H15-13H15, 0.5, 1.1, 1.4,1.5, AMPHI",
    examDate: "26/05/2025T14:00:00Z",
  },
  "structure-donnees-c": {
    chapters: ["Tableaux et listes chaînées", "Piles et files", "Arbres binaires", "Tables de hachage", "Graphes"],
    resources: ["Polycopié du cours", "Travaux pratiques", "Projets"],
    schedule: "MARDI 14H30-16H30, 0.5, 1.1, 1.4,1.5, AMPHI",
    examDate: "27/05/2025T09:00:00Z",
  },
  "systeme-exploitation": {
    chapters: ["Processus et threads", "Ordonnancement", "Gestion de la mémoire", "Systèmes de fichiers", "Sécurité"],
    resources: ["Polycopié du cours", "Travaux pratiques", "Projets"],
    schedule: "MARDI 16H45-18H45, 0.5, 1.1, 1.4,1.5, AMPHI",
    examDate: "27/05/2025T14:00:00Z",
  },
}
